theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon"
title: "Kevin Ma"
description: "Kevin Ma's homepage."
author:
  name     : "Kevin Ma"
  bio      : "PhD in Cellular and Molecular Biology"
  location : "Beijing, China" 
